steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/banbagroup.com:$COMMIT_SHA'
      - '--tag=gcr.io/$PROJECT_ID/banbagroup.com:latest'
      - '--file=Dockerfile'      
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/banbagroup.com:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/banbagroup.com:latest'
tags:
  - '$COMMIT_SHA'
