---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "banbagroup"
  namespace: "default"
  labels:
    app: "banbagroup"
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: "banbagroup"
  template:
    metadata:
      labels:
        app: "banbagroup"
    spec:
      containers:
        - name: "banbagroup"
          image:  "${DOCKER_IMAGE}"          
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "banbagroup-hpa"
  namespace: "default"
  labels:
    app: "banbagroup"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "banbagroup"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    [ "8.8.8.8", "8.8.4.4" ]
